ROOMS_FACEBOOK_APP_ID: "1212909670934343"
ROOMS_FACEBOOK_SECRET: "e9219fdebaee1133535cc000d454545"

ROOMS_MAIL_PASSWORD_DEV: "fake_password"
ROOMS_MAIL_USERNAME_DEV: "my@my.com"
ROOMS_MAIL_HOST_DEV: "localhost:3000"

ROOMS_MAIL_PASSWORD_PRO: "fake_password"
ROOMS_MAIL_USERNAME_PRO: "myemail@myemail.com"
ROOMS_MAIL_HOST_PRO: "sleepy-scrubllll-9999.herokuapp.com"

ROOMS_IMAGE_MAGICK_PATH: "/usr/bin/"


